---
- hosts: localhost
  become: true
  connection: local
  tasks:
    - name: Configuring NGINX Load-Balancing
      template:
        src: "/streams.conf.j2"
        dest: "/etc/nginx/stream.d/streams.conf"
