---
- hosts: localhost
  become: true
  connection: local
  vars:
    rancher_gen_dl: '{{ rancher_gen_url }}/{{ rancher_gen_version }}/{{ rancher_gen_file }}'
    rancher_gen_file: 'rancher-gen-linux-amd64.tar.gz'
    rancher_gen_version: 'v0.2.0'
    rancher_gen_url: 'https://github.com/janeczku/go-rancher-gen/releases/download'
  tasks:
    - name: Updating Apt-Cache
      apt:
        update_cache: yes

    - name: Installing NGINX
      apt:
        name: "nginx"
        state: "present"
        install_recommends: no

    - name: Installing Add'l Packages
      apt:
        name: "{{ item }}"
        state: "present"
        install_recommends: no
      with_items:
        - 'python-pip'
        - 'rsyslog'
        - 'supervisor'

    - name: Disabling Default NGINX Site
      file:
        dest: "/etc/nginx/sites-enabled/default"
        state: "absent"

    - name: Configuring NGINX
      template:
        src: "/nginx.conf.j2"
        dest: "/etc/nginx/nginx.conf"

    - name: Ensuring Folders exist
      file:
        path: "{{ item }}"
        state: "directory"
      with_items:
        - '/run/nginx'
        - '/etc/nginx/stream.d'

    - name: Installing Rancher-Gen
      pip:
        name: "rancher-gen"
        state: "present"
