---
- hosts: localhost
  become: true
  connection: local
  tasks:
    - name: Updating Apt-Cache
      apt:
        update_cache: yes

    - name: Installing NGINX
      apt:
        name: "nginx"
        state: "present"
        install_recommends: no

    - name: Installing Add'l Packages
      apt:
        name: "{{ item }}"
        state: "present"
        install_recommends: no
      with_items:
        - 'rsyslog'
        - 'supervisor'

    - name: Disabling Default NGINX Site
      file:
        dest: "/etc/nginx/sites-enabled/default"
        state: "absent"

    - name: Configuring NGINX
      template:
        src: "/nginx.conf.j2"
        dest: "/etc/nginx/nginx.conf"

    - name: Ensuring Folders exist
      file:
        path: "{{ item }}"
        state: "directory"
      with_items:
        - '/run/nginx'
        - '/etc/nginx/stream.d'
